#!/usr/bin/env bash
set -eu
set -o pipefail
#

usage="Usage: $(basename $0) [-h][-c]
    -h - help
    -c - check

Prints a short lived access token for jira-app
"

check="no"
while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?)
            echo "$usage"
            exit 0
        ;;
        -c)
            check="yes"
        ;;
        *)
            break
        ;;
    esac
    shift
done

if [ -z "${GOOGLE_TOKEN_URI:-}" ]; then
    echo "Error: GOOGLE_TOKEN_URI not defined" 1>&2
    exit 1
fi

if [ -z "${GOOGLE_CLIENT_ID:-}" ]; then
    echo "Error: GOOGLE_CLIENT_ID not defined" 1>&2
    exit 1
fi

if [ -z "$GOOGLE_CLIENT_SECRET" ]; then
    echo "Error: GOOGLE_CLIENT_SECRET not defined" 1>&2
    exit 1
fi

if [ -z "$APP_REFRESH_TOKEN" ]; then
    echo "Error: APP_REFRESH_TOKEN not defined" 1>&2
    exit 1
fi

TOKEN_RESPONSE=$(curl -s -X POST $GOOGLE_TOKEN_URI \
  -d client_id=$GOOGLE_CLIENT_ID \
  -d client_secret=$GOOGLE_CLIENT_SECRET \
  -d refresh_token=$APP_REFRESH_TOKEN \
  -d grant_type=refresh_token)

ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.id_token')

if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
  echo "Error: Failed to retrieve access token" 1>&2
  exit 1
fi

echo "$ACCESS_TOKEN"

if [ "$check" == "yes" ]; then
  echo 
  curl -H "Authorization: Bearer $ACCESS_TOKEN" 'https://www.googleapis.com/oauth2/v3/tokeninfo'
fi

