#!/usr/bin/env bash
set -eu
set -o pipefail
#

SCOPES="openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
SCOPES="$(echo "$SCOPES" | sed 's/ /%20/g')"

usage="Usage: $(basename $0) [-h] credentials_json_file [code]
    -h - help
    credentials_json_file
    code

Gets a refresh_token
"

while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?)
            echo "$usage"
            exit 0
        ;;
        *)
            break
        ;;
    esac
    shift
done

CREDENTIALS_FILE="${1:-}"
if [ -z "$CREDENTIALS_FILE" ]; then
    echo "Error: no credentials json file specified, please download from google (can only download on create) and specify file as parameter"
    exit 1
fi

CLIENT_ID=$(jq -r '.web.client_id' "$CREDENTIALS_FILE")
CLIENT_SECRET=$(jq -r '.web.client_secret' "$CREDENTIALS_FILE")
TOKEN_URI=$(jq -r '.web.token_uri' "$CREDENTIALS_FILE")
REDIRECT_URI=$(jq -r '.web.redirect_uris[0]' "$CREDENTIALS_FILE")

CODE="${2:-}"
if [ -z "$CODE" ]; then
  echo "Paste this url in your browser, then get the code parameter (note %2F is /) from the google redirect url and rerun this script"
  echo "  https://accounts.google.com/o/oauth2/auth?client_id=$CLIENT_ID&redirect_uri=$REDIRECT_URI&response_type=code%20id_token&scope=$SCOPES&access_type=offline&prompt=consent"
  exit 1
fi

curl "$TOKEN_URI" \
  -d client_id="$CLIENT_ID" \
  -d client_secret="$CLIENT_SECRET" \
  -d code="$CODE" \
  -d grant_type=authorization_code \
  -d redirect_uri="$REDIRECT_URI" 

