#!/usr/bin/env bash
set -eu
set -o pipefail

usage="Usage: $(basename $0) [-h][-r][-f]
    -h - help
    -r - restart
    -f - run in foreground

Starts the jira-app in the background
"
APP_PROFILE="${BEEP_BOOP_PROFILE:-prod}"

restart=0
foreground=0
while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?)
            echo "$usage"
            exit 0
        ;;
        -r)
            restart=1
        ;;
	-f)
            foreground=1
	;;
        *)
	    break
        ;;
    esac
    shift
done

if [ -z "$AI_HOME" ]; then
    echo "Error: AI_HOME not defined, have you setup the environment" 1>&2
    exit 1
fi

if [ -z "$EXTOLE_SUPER_USER_API_KEY" ]; then
    echo "Error: no environment variable EXTOLE_SUPER_USER_API_KEY" 1>&2
    exit 1
fi

if ! command -v java &>/dev/null; then
    echo "Error: java not found" 1>&2
    exit 1
fi

app_home=$AI_HOME/jira-app

mkdir -p $app_home/logs

jar="$(find $app_home/build/libs -name "jira-app*SNAPSHOT.jar" | grep -v "plain.jar" | sort | tail -1)"

if [ $restart -eq 1 ]; then
    if pgrep -n -f $jar >/dev/null; then
        echo -n "jira-app stopping..."
        pkill -f $jar

        end=$((SECONDS+240))
        while pgrep -f $jar >/dev/null; do
            if [ $SECONDS -ge $end ]; then
                echo "failed."
                echo "Failed to stop jira-app within 2 minutes." 1>&2
                exit 1
            fi
            sleep 5
            echo -n "."
        done
        echo "stopped."
    fi
fi

if pgrep -f build/libs/jira-app >/dev/null; then
    echo "jira-app already running on $(pgrep -f libs/jira-app)"
    exit 0
fi

echo "jira-app $jar last modified $(stat -c '%y' $jar)"

cd $app_home
app_command=(java -jar "$jar" --spring.profiles.active="$APP_PROFILE")

if [ "$foreground" == "1" ]; then
    echo "jira-app running: ${app_command[*]}"
    "${app_command[@]}"
else
    log="$app_home/logs/app-output.log"
    echo "jira-app running in background, logs: $log"
    nohup "${app_command[@]}" > "$log" 2>&1 &
    pid=$!
    echo "jira-app running in background as process: $pid"

    timeout=60
    port=8090
    interval=1
    echo "jira-app waiting for port $port to be available (timeout: ${timeout}s)..."

    until ss -anp | grep -q ":$port"; do
        sleep $interval
        timeout=$((timeout - interval))
        if [ $timeout -le 0 ]; then
            echo "jira-app timeout reached. Port $port is not being listened on."
            tail -100 "$log"
            exit 1
        fi
    done

    echo "jira-app port $port is now being listened on."
    exit 0
fi
